services:
  arc42-builder:
    build: .
    image: arc42-generator:9.1.0
    container_name: arc42-generator-build
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: ./build-arc42.sh
